/**
 * Curated registry of known ActiveCommunities tenants (org slugs).
 *
 * There is no upstream discovery endpoint — see docs/activenet-api.md — so this
 * list is enumerated out-of-band (search-engine dorking + candidate slugs, each
 * validated live against GET /{slug}/rest/activities/filters) and baked in.
 * Honest but not exhaustive; any live slug works with the tools even if absent
 * here. Zero sites+centers+seasons = registered but effectively dormant.
 * "name" is the tenant portal <title> — some are generic.
 *
 * Canadian ActiveNet tenants (e.g. Vancouver) live on a different host
 * (anc.ca.apm.activecommunities.com) and are not covered by this registry.
 */
export const TENANTS_VALIDATED = "2026-08-16";

export const TENANTS = [
  { slug: "aareced", name: "REC&ED - Online Recreation Activities", sites: 1, centers: 50, seasons: 73 },
  { slug: "aarecparks", name: "Online Services", sites: 108, centers: 89, seasons: 0 },
  { slug: "ahpd", name: "AHPD Registration", sites: 41, centers: 30, seasons: 32 },
  { slug: "albemarlecountyrec", name: "ACPR-Online Registration", sites: 0, centers: 2, seasons: 0 },
  { slug: "alleghenyparks", name: "Allegheny Parks - Online Services", sites: 0, centers: 10, seasons: 0 },
  { slug: "atlantadprca", name: "Atlanta DPR Online Services", sites: 0, centers: 44, seasons: 0 },
  { slug: "auburnwa", name: "Auburn Parks Online", sites: 0, centers: 22, seasons: 0 },
  { slug: "bellingham", name: "EZ Reg - Bellingham Parks and Recreation", sites: 0, centers: 9, seasons: 0 },
  { slug: "brushrec", name: "ActiveNet - Online Recreation Activities", sites: 1, centers: 0, seasons: 0 },
  { slug: "buenapark", name: "City of Buena Park Community Services", sites: 0, centers: 15, seasons: 43 },
  { slug: "burnaby131", name: "Parks & Recreation Online Registration", sites: 1, centers: 2, seasons: 0 },
  { slug: "carlislerec", name: "Carlisle Parks and Recreation - Online Registration", sites: 0, centers: 0, seasons: 5 },
  { slug: "carmelclayparks", name: "Carmel Clay Parks & Recreation Online Registration", sites: 0, centers: 21, seasons: 4 },
  { slug: "chandleraz", name: "Chandler Online", sites: 0, centers: 17, seasons: 0 },
  { slug: "chesterfieldparksrec", name: "Chesterfield County, VA - Online Registration and Reservation", sites: 0, centers: 62, seasons: 4 },
  { slug: "chicagoparkdistrict", name: "CPD Transaction Portal", sites: 0, centers: 352, seasons: 6 },
  { slug: "cityofindianola", name: "Indianola Parks and Recreation Online Services", sites: 0, centers: 5, seasons: 0 },
  { slug: "cityofrichmond", name: "Richmond Parks and Recreation Online Services", sites: 0, centers: 6, seasons: 0 },
  { slug: "cityofwilsonville", name: "ActiveNet - Online Recreation Activities", sites: 1, centers: 10, seasons: 0 },
  { slug: "columbusrecparks1", name: "Columbus Recreation and Parks", sites: 0, centers: 39, seasons: 0 },
  { slug: "concordparksrec", name: "ActiveNet - Online Recreation Activities", sites: 0, centers: 0, seasons: 0 },
  { slug: "coralvillerecreation", name: "Coralville Parks and Recreation - Online Registration", sites: 0, centers: 4, seasons: 0 },
  { slug: "covington", name: "ActiveNet - Online Recreation Activities", sites: 3, centers: 2, seasons: 26 },
  { slug: "cprd", name: "ActiveNet - Online Recreation Activities", sites: 0, centers: 0, seasons: 0 },
  { slug: "cupertino", name: "City of Cupertino - Online Services", sites: 0, centers: 20, seasons: 0 },
  { slug: "dalycity", name: "iplay - City of Daly City", sites: 0, centers: 10, seasons: 0 },
  { slug: "denver", name: "Denver Parks & Recreation Online", sites: 57, centers: 70, seasons: 0 },
  { slug: "desertrecdistrict", name: "Desert Recreation District Online Registration Site", sites: 0, centers: 51, seasons: 0 },
  { slug: "elktonpr", name: "Elkton Parks and Recreation Online Registration", sites: 0, centers: 0, seasons: 0 },
  { slug: "elmhurstparks", name: "Elmhurst Park District", sites: 0, centers: 33, seasons: 0 },
  { slug: "fitchburg", name: "ActiveNet - Online Recreation Activities", sites: 0, centers: 0, seasons: 0 },
  { slug: "frederickcntyparksandrec", name: "Frederick County Parks & Recreation", sites: 0, centers: 39, seasons: 0 },
  { slug: "fremont", name: "City of Fremont", sites: 0, centers: 28, seasons: 0 },
  { slug: "gainesvilleparksandrec", name: "City of Gainesville Parks, Recreation and Cultural Affairs", sites: 3, centers: 16, seasons: 30 },
  { slug: "gaithersburgmd", name: "Gaithersburg Parks and Recreation Online Registration", sites: 0, centers: 30, seasons: 14 },
  { slug: "grandprairie", name: "ActiveNET: Grand Prairie's Parks, Arts & Recreation Registration System", sites: 0, centers: 5, seasons: 0 },
  { slug: "henricorecandparks", name: "Henrico County Recreation and Parks Online Registration", sites: 0, centers: 56, seasons: 0 },
  { slug: "hillsborooregonparks", name: "Online Registration | Hillsboro Parks & Recreation", sites: 0, centers: 13, seasons: 0 },
  { slug: "holmenwirec", name: "ActiveNet - Online Recreation Activities", sites: 2, centers: 7, seasons: 4 },
  { slug: "houstonparks", name: "Houston Parks and Recreation Department Online", sites: 5, centers: 124, seasons: 0 },
  { slug: "howardcounty", name: "Welcome to Howard County Online Services", sites: 0, centers: 149, seasons: 0 },
  { slug: "indyparks", name: "Indy Parks & Recreation", sites: 59, centers: 42, seasons: 18 },
  { slug: "iowacityrecreation", name: "Iowa City - Online Recreation Activities", sites: 1, centers: 20, seasons: 8 },
  { slug: "irvingrec", name: "ActiveNet - Online Recreation Activities", sites: 0, centers: 14, seasons: 21 },
  { slug: "janesvilleleisure", name: "Janesville Recreation Division Online Registration", sites: 0, centers: 4, seasons: 0 },
  { slug: "kansascityymca", name: "YMCA of Greater Kansas City - Registration", sites: 63, centers: 124, seasons: 0 },
  { slug: "kentparkandrec", name: "Kent Parks and Recreation Online Registration", sites: 0, centers: 2, seasons: 0 },
  { slug: "kentparksandrec", name: "ActiveNet - Online Recreation Activities", sites: 5, centers: 7, seasons: 0 },
  { slug: "lakeoswegoparks", name: "City of Lake Oswego Parks and Recreation", sites: 0, centers: 14, seasons: 0 },
  { slug: "losangelescounty", name: "Los Angeles County Online Reservations and Registration", sites: 138, centers: 123, seasons: 0 },
  { slug: "mabparksrec", name: "ActiveNet - Online Recreation Activities", sites: 1, centers: 15, seasons: 0 },
  { slug: "marysvillewa", name: "City of Marysville Online Services", sites: 0, centers: 13, seasons: 0 },
  { slug: "mca", name: "ActiveNet - Online Recreation Activities", sites: 0, centers: 7, seasons: 1 },
  { slug: "mcgawymca", name: "McGaw YMCA Registration System", sites: 0, centers: 1, seasons: 0 },
  { slug: "mcminnvilleparksandrec", name: "McMinnville Parks and Recreation Online Registration", sites: 0, centers: 3, seasons: 0 },
  { slug: "mcpr", name: "Montgomery County Parks and Recreation", sites: 0, centers: 4, seasons: 2 },
  { slug: "mecklenburgparks", name: "ActiveNet - Online Recreation Activities", sites: 40, centers: 0, seasons: 12 },
  { slug: "missouricitytx", name: "Missouri City - Online Registration", sites: 1, centers: 2, seasons: 0 },
  { slug: "moseslake", name: "Moses Lake Parks, Recreation & Cultural Services", sites: 0, centers: 12, seasons: 0 },
  { slug: "mplsparkandrec", name: "MPRB Online Recreation Services", sites: 0, centers: 111, seasons: 4 },
  { slug: "munster", name: "Online Services", sites: 0, centers: 13, seasons: 0 },
  { slug: "napervilleparks", name: "Naperville Park District Online Registration", sites: 0, centers: 112, seasons: 0 },
  { slug: "newlondon", name: "New London Parks and Recreation Online Registration", sites: 0, centers: 0, seasons: 0 },
  { slug: "obparks", name: "Oak Brook Park District Online Registration and Memberships", sites: 0, centers: 4, seasons: 0 },
  { slug: "orlando", name: "City of Orlando Parks and Recreation", sites: 0, centers: 22, seasons: 18 },
  { slug: "palmdale", name: "Online Services", sites: 0, centers: 12, seasons: 0 },
  { slug: "phoenix", name: "Phoenix Parks and Recreation Online", sites: 0, centers: 79, seasons: 0 },
  { slug: "planoparksandrec", name: "Online Services", sites: 0, centers: 16, seasons: 0 },
  { slug: "playgarland", name: "Online Services", sites: 0, centers: 11, seasons: 0 },
  { slug: "portercountyparks", name: "Online Services", sites: 0, centers: 2, seasons: 12 },
  { slug: "portlandparks", name: "Portland Parks & Recreation", sites: 35, centers: 40, seasons: 6 },
  { slug: "putnamcounty", name: "ActiveNet - Online Recreation Activities", sites: 2, centers: 0, seasons: 0 },
  { slug: "richardsontx", name: "City of Richardson Parks and Recreation - Online Services", sites: 0, centers: 15, seasons: 8 },
  { slug: "rwcpark", name: "Online Registration- Redwood City Parks and Recreation", sites: 9, centers: 15, seasons: 10 },
  { slug: "santaclara", name: "Santa Clara Parks & Recreation", sites: 0, centers: 17, seasons: 0 },
  { slug: "santamaria", name: "Santa Maria Online Services", sites: 0, centers: 17, seasons: 6 },
  { slug: "santamonicarecreation", name: "ActiveNet - Online Recreation Activities", sites: 0, centers: 36, seasons: 0 },
  { slug: "scottsdale", name: "City of Scottsdale - Online Services", sites: 0, centers: 39, seasons: 0 },
  { slug: "sdparkandrec", name: "SD RecConnect Your Online Connection To Recreation and Leisure Experiences", sites: 76, centers: 128, seasons: 10 },
  { slug: "seattle", name: "Seattle Parks and Recreation", sites: 98, centers: 82, seasons: 8 },
  { slug: "sfrecpark", name: "SF Rec Online Registration", sites: 0, centers: 85, seasons: 23 },
  { slug: "shorelinewa", name: "-", sites: 0, centers: 15, seasons: 9 },
  { slug: "snoco", name: "ActiveNet - Online Recreation Activities", sites: 1, centers: 1, seasons: 0 },
  { slug: "stcparks", name: "Online Registration - St. Charles Park District", sites: 0, centers: 37, seasons: 0 },
  { slug: "thecommunityhouse", name: "ActiveNet - Online Recreation Activities", sites: 0, centers: 0, seasons: 0 },
  { slug: "tigard", name: "Tigard Parks & Rec", sites: 0, centers: 6, seasons: 16 },
  { slug: "townandcountry", name: "ActiveNet - Online Recreation Activities", sites: 1, centers: 0, seasons: 0 },
  { slug: "tucsonparksandrec", name: "Tucson Parks and Recreation EZEEreg", sites: 0, centers: 33, seasons: 0 },
  { slug: "upland", name: "Online Services", sites: 0, centers: 19, seasons: 0 },
  { slug: "urbanaparks", name: "Urbana Park District - Online Registration", sites: 0, centers: 20, seasons: 0 },
  { slug: "vbparksrec", name: "Virginia Beach Parks & Recreation Online Registration", sites: 0, centers: 69, seasons: 0 },
  { slug: "villageofbellevue", name: "Village of Bellevue Parks, Recreation & Forestry", sites: 1, centers: 5, seasons: 0 },
  { slug: "visalia", name: "a", sites: 0, centers: 9, seasons: 0 },
  { slug: "walthamrecreation", name: "Waltham Recreation Department - Online Registration", sites: 0, centers: 0, seasons: 0 },
  { slug: "washingtonncrec", name: "ActiveNet - Online Recreation Activities", sites: 2, centers: 1, seasons: 0 },
  { slug: "waunakee", name: "ActiveNet - Online Recreation Activities", sites: 1, centers: 19, seasons: 0 },
  { slug: "waupacaparknrec", name: "City of Waupaca Parks and Recreation Online Services", sites: 0, centers: 0, seasons: 0 },
  { slug: "wenatcheeparksandrec", name: "Online Services", sites: 0, centers: 0, seasons: 0 },
  { slug: "westminstercityrec", name: "ActiveNet - Online Recreation Activities", sites: 0, centers: 0, seasons: 50 },
  { slug: "wilcotxparks", name: "Online Services", sites: 0, centers: 0, seasons: 0 },
  { slug: "wylie", name: "City of Wylie Parks and Recreation Online Registration", sites: 0, centers: 4, seasons: 3 },
];
